#!/bin/bash

set -e

echo "Post Build"
IFS=' ' read -r -a tags <<< $(git tag --contains | tr '\n' ' ')

for tag in "${tags[@]}"
do
    echo "Tagging as \"$tag\""
    docker tag $IMAGE_NAME $DOCKER_REPO:$tag
    docker push $DOCKER_REPO:$tag
done
