#!/bin/bash
set -e

docker run -a stdin -a stdout -v $(pwd):/host debian /bin/bash -c '
  cd /host;
  apt-get update;
  apt-get install -y \
    wget \
    unzip \
    bc \
    cpio \
    python \
    rsync \
    build-essential;
  export BR2_EXTERNAL=/host;
  make -f "Makefile.toolchain";
  make -f "Makefile.$SOURCE_BRANCH";
'
